name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - name: Install build dependencies
      run: sudo apt install -y build-essential libasound2-dev 
    - uses: actions/checkout@v1
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
